### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by aspiers** [itsananderson/itsananderson.github.io#1]
Hi,

I recently wrote a [blog post](http://blog.adamspiers.org/2015/03/24/why-and-how-to-correctly-amend-github-pull-requests/) which linked to:
- http://willi.am/blog/2014/08/12/the-dark-side-of-the-force-push/

but now that URL gives a 404 and I can't find the new location via your site's search.

**Comment by itsananderson** [comment]
Thanks for the heads up (and the link :))

It looks like the date somehow got shifted by a day on that post and a few others. I probably did something dumb when I published my last post. I should have a chance to fix it tomorrow

—

**Comment by itsananderson** [comment]
Turns out it wasn't my fault (this time). I was traveling in another timezone when I published my last post. Apparently the 2 hour time difference shifted my late-night posts into the next day, which changed their URLs. I just republished from the correct timezone, which should fix the links.

Thanks again for the heads-up!

**Comment by aspiers** [comment]
Cool, thanks! :)
